spring:
  datasource:
    url:  jdbc:sqlserver://chandrasqlserver.database.windows.net:1433;database=mysqlserverdb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: chandra
    password: password@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect:  org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191